# Generated by Django 3.1.7 on 2021-02-25 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TR_buy_inf', models.DecimalField(decimal_places=5, max_digits=10)),
                ('TR_buy_sup', models.DecimalField(decimal_places=5, max_digits=10)),
                ('TR_sell_inf', models.DecimalField(decimal_places=5, max_digits=10)),
                ('TR_sell_sup', models.DecimalField(decimal_places=5, max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
