# Generated by Django 3.1.7 on 2021-02-25 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_watch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='TR_buy_inf',
            new_name='price_buy',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='TR_buy_sup',
            new_name='price_sell',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='TR_sell_inf',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='TR_sell_sup',
        ),
    ]
